# Generated by Django 5.0.6 on 2024-06-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='social.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_ky',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='social.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='user_ru',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='social.userprofile'),
        ),
    ]
